import csv
import re
from pathlib import Path
from collections import Counter


# Base directory where all batch experiment results are stored.
BASE_WORK_ROOT = Path.home() / "gitbug-batch"

# Original CSV generated by run_screened_bugs.py
RESULTS_CSV = BASE_WORK_ROOT / "results.csv"

# Output CSV with extracted EvoSuite metrics added
OUT_CSV = BASE_WORK_ROOT / "results_with_metrics.csv"


def parse_coverage_metrics(log_path: Path) -> dict:
    """
    Parse EvoSuite coverage metrics from a single evosuite_fixed.log file.

    The function looks for lines such as:

        Coverage of criterion LINE: 100%
        Coverage of criterion BRANCH: 94%
        Coverage of criterion WEAKMUTATION: 97%
        Number of covered goals: 37

    and extracts those values into a dictionary.
    """

    metrics = {
        "line_coverage": "",
        "branch_coverage": "",
        "weakmutation_score": "",
        "line_goals": "",
        "branch_goals": "",
        "weakmutation_goals": "",
    }

    # If the log file does not exist, return empty metrics.
    if not log_path.is_file():
        return metrics

    current_criterion = None

    # Regex patterns used to extract EvoSuite metrics.
    coverage_re = re.compile(r"Coverage of criterion (\w+): ([0-9]+)%")
    goals_re = re.compile(r"Number of covered goals: ([0-9]+)")

    with open(log_path, encoding="utf-8", errors="replace") as f:
        for line in f:

            # Check if the line contains a coverage percentage.
            coverage_match = coverage_re.search(line)

            if coverage_match:
                current_criterion = coverage_match.group(1)
                value = coverage_match.group(2)

                if current_criterion == "LINE":
                    metrics["line_coverage"] = value

                elif current_criterion == "BRANCH":
                    metrics["branch_coverage"] = value

                elif current_criterion == "WEAKMUTATION":
                    metrics["weakmutation_score"] = value

                continue

            # Check if the line contains the number of covered goals.
            goals_match = goals_re.search(line)

            if goals_match and current_criterion:
                goals = goals_match.group(1)

                if current_criterion == "LINE":
                    metrics["line_goals"] = goals

                elif current_criterion == "BRANCH":
                    metrics["branch_goals"] = goals

                elif current_criterion == "WEAKMUTATION":
                    metrics["weakmutation_goals"] = goals

                current_criterion = None

    return metrics


def main() -> None:
    """
    Main pipeline.

    For each experiment row in results.csv:
        1. Locate the corresponding evosuite_fixed.log
        2. Extract coverage metrics
        3. Append those metrics into a new CSV row

    Finally:
        - write results_with_metrics.csv
        - print a small terminal summary of result categories
    """

    rows = []

    with open(RESULTS_CSV, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        for row in reader:

            # Each experiment has its own logs directory.
            logs_dir = Path(row["logs_dir"])

            # EvoSuite generation log.
            evosuite_log = logs_dir / "evosuite_fixed.log"

            # Extract metrics from the EvoSuite log.
            metrics = parse_coverage_metrics(evosuite_log)

            # Merge original CSV row with extracted metrics.
            new_row = dict(row)
            new_row.update(metrics)

            rows.append(new_row)

    # Output column order for the final CSV.
    fieldnames = [
        "bug_id",
        "class_under_test",
        "seed",
        "java_version",
        "exit_code",
        "fixed_result",
        "buggy_result",
        "result",
        "conclusion",
        "line_coverage",
        "branch_coverage",
        "weakmutation_score",
        "line_goals",
        "branch_goals",
        "weakmutation_goals",
        "work_root",
        "logs_dir",
    ]

    # Write final CSV with extracted metrics.
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")

        writer.writeheader()
        writer.writerows(rows)

    print(f"Wrote metrics to {OUT_CSV}")

    # Count how many times each experiment result appears.
    result_counts = Counter(row.get("result", "") for row in rows)

    print("\nResult summary:")

    for result, count in sorted(result_counts.items()):
        print(f"{count:7} {result}")


if __name__ == "__main__":
    main()